### ISSUE TITLE
How should I modify the weapon damage?

### ISSUE THREAD

**Issue by Catfish872** [CenturionAU/space-marine-2-default-other#2]
Thanks for the mod and I really like it. The official game does not represent Power Imaging enough and the game difficulty can be over challenging. This mod helped me a lot to better enjoy the game.
10x damage might be too high (3x I think may be ok). I wonder if I want to modify the damage, are there only "damage" in "firearm_library_pve.sso" and "impulse" in "melee_xxx_desc.sso" to be modified? Do I need to modify the "ModificatorDamageAmount" in "firearm_modificators_library.sso" ?

**Comment by CenturionAU** [comment]
For ranged weapons, within ```ssl/weapons/creator/firearm_library_pve.sso```, I modified the damage by editing ```damage   =   ``` within ```shotCreatorSettings ``` under ```shellDescriptions``` of each weapon I wanted to edit. There may be a way to blanket edit, for example, ```"bolter_bullet"``` but I am not personally aware of such a method. Should you find such a method, I'd definitely like to know about it but the aforementioned steps is how I edit the damage values of each ranged player weapon.

You will also need to go into ```ssl/weapons/creator/customization/firearm_modificators_library.sso``` and change the same variable as above in order to edit the auxiliary grenade launchers found on the Bolt Rifle.

For melee weapons, you'll need to go into ```ssl/weapons/melee/weapon_descriptions/melee_weapon_descs/```. This folder contains an ```.sso``` file for each individual melee weapon, including that of the NPCs. The files I edited were for the chainsword, combat knife, firearm (heavy melee), power fist, power sword, and thunder hammer respectively. Each file is named in this convention. Within each file, there'll be a variable named ```healthDamage``` in line 5 or 6. This is the variable I edited to change the damage value of each melee weapons.

So yeah, that's how I edited the damage values of all player ranged and melee weapons. The method I use is a bit repetitive but it's very simple and easy to understand and hope you can use it to your preferences, unless you find a better method.

Just as a note, you can reverse engineer someone else's ```.sso``` modifications by comparing them with their vanilla counterparts - I recommend using VS Code's Compare feature for this. This allows you to see how lines of code are different from the vanilla files and thereby allow you to see what they changed to achieve whatever it is that their modification does.

**Comment by Catfish872** [comment]
> For ranged weapons, within `ssl/weapons/creator/firearm_library_pve.sso`, I modified the damage by editing `damage = ` within `shotCreatorSettings ` under `shellDescriptions` of each weapon I wanted to edit. There may be a way to blanket edit, for example, `"bolter_bullet"` but I am not personally aware of such a method. Should you find such a method, I'd definitely like to know about it but the aforementioned steps is how I edit the damage values of each ranged player weapon.
> 
> You will also need to go into `ssl/weapons/creator/customization/firearm_modificators_library.sso` and change the same variable as above in order to edit the auxiliary grenade launchers found on the Bolt Rifle.
> 
> For melee weapons, you'll need to go into `ssl/weapons/melee/weapon_descriptions/melee_weapon_descs/`. This folder contains an `.sso` file for each individual melee weapon, including that of the NPCs. The files I edited were for the chainsword, combat knife, firearm (heavy melee), power fist, power sword, and thunder hammer respectively. Each file is named in this convention. Within each file, there'll be a variable named `healthDamage` in line 5 or 6. This is the variable I edited to change the damage value of each melee weapons.
> 
> So yeah, that's how I edited the damage values of all player ranged and melee weapons. The method I use is a bit repetitive but it's very simple and easy to understand and hope you can use it to your preferences, unless you find a better method.
> 
> Just as a note, you can reverse engineer someone else's `.sso` modifications by comparing them with their vanilla counterparts - I recommend using VS Code's Compare feature for this. This allows you to see how lines of code are different from the vanilla files and thereby allow you to see what they changed to achieve whatever it is that their modification does.

Thanks for the reply. I managed to modify both range and melee damage. This mod is exactly what I need, this game truly needs to rebalance player and enemy ability.
